# Generated by Django 6.0.7 on 2026-07-29 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('public', models.BooleanField(default=True)),
                ('about', models.TextField(blank=True, default='', max_length=300)),
                ('tipo', models.CharField(choices=[('CLIENT', 'client'), ('ADMIN', 'admin')], default='CLIENT', max_length=6)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['username'],
            },
        ),
    ]
