# Generated by Django 6.0.8 on 2026-08-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='reason',
            field=models.TextField(default='Motivo não especificado'),
            preserve_default=False,
        ),
    ]
